### ISSUE TITLE
I cannot see the text in the windows

### ISSUE THREAD

**Issue by PabloCastellano** [webanck/docker-wine-steam#1]
It has been working fine for 3 days until now. See the attached screenshot.

![screenshot from 2015-07-05 12 01 44](https://cloud.githubusercontent.com/assets/73274/8511207/cb6eb288-230d-11e5-9f3c-2c865abe9683.png)

**Comment by webanck** [comment]
That's pretty strange, have you tried to rebuild the container image since it happenned?
Could you try and paste the logs from the build script?

**Comment by webanck** [comment]
Ok, I rebuilt my container from scratch and tested, it's working.
Without any further answer I am closing this issue.
