### ISSUE TITLE
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error

### ISSUE THREAD

**Issue by robbeofficial** [webanck/docker-wine-steam#12]
pulseaudio 8.0 is running properly on host (Ubuntu 16.04.2 LTS)

after running finalize_installation and pressing the _Audio_ tab of the wine configuration tool, wine crashes throwing the following error message:

shm_open() failed: No such file or directory
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error

same happens after running steam.

any ideas?

**Comment by webanck** [comment]
I tracked this error which is in fact caused by other programs tinkering with pulseaudio's shared memory files in /dev/shm (see [pulseaudio bug report](https://bugs.freedesktop.org/show_bug.cgi?id=92141)).
A workaround is to disable the pulseaudio shared memory when creating the docker image:
```
sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/daemon.conf
sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf
```
