### ISSUE TITLE
gpg: failed to start agent '/usr/bin/gpg-agent': No such file or directory

### ISSUE THREAD

**Issue by danmash** [webanck/docker-wine-steam#18]
Hi, while running `builder.sh` I have a following error
 
2019-01-09 10:55:42--  https://dl.winehq.org/wine-builds/Release.key
Resolving dl.winehq.org (dl.winehq.org)... 151.101.2.217, 151.101.66.217, 151.101.130.217, ...
Connecting to dl.winehq.org (dl.winehq.org)|151.101.2.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3122 (3.0K) [application/pgp-keys]
Saving to: 'Release.key'

     0K ...                                                   100% 21.4M=0s

2019-01-09 10:55:43 (21.4 MB/s) - 'Release.key' saved [3122/3122]

Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: failed to start agent '/usr/bin/gpg-agent': No such file or directory
gpg: can't connect to the agent: No such file or directory
The command '/bin/sh -c dpkg --add-architecture i386 && 	apt-get update && 	apt-get upgrade -y && 	apt-get install -y --no-install-recommends software-properties-common apt-transport-https wget && 	add-apt-repository ppa:graphics-drivers/ppa && 	wget -nc https://dl.winehq.org/wine-builds/Release.key && apt-key add Release.key && add-apt-repository https://dl.winehq.org/wine-builds/ubuntu/ && 	apt-get update && 	apt-get install -y --no-install-recommends initramfs-tools nvidia-384 && 	apt-get install -y --no-install-recommends winehq-stable cabextract unzip p7zip zenity && 	wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && chmod +x winetricks && mv winetricks /usr/local/bin && apt-get install -y --no-install-recommends winbind && 	apt-get install -y --no-install-recommends p11-kit-modules:i386 libp11-kit-gnome-keyring:i386 && 	apt-get install -y --no-install-recommends pulseaudio:i386 && 	sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/daemon.conf && 	sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf && 	su -p -l wine -c 'winecfg && wineserver --wait' && 	su -p -l wine -c 'winetricks -q winxp && wineserver --wait' && 	su -p -l wine -c 'winetricks -q sound=pulse && wineserver --wait' && 	su -p -l wine -c 'winetricks -q corefonts && wineserver --wait' && 	su -p -l wine -c 'winetricks -q dotnet40 && wineserver --wait' && 	su -p -l wine -c 'winetricks -q xna40 && wineserver --wait' && 	su -p -l wine -c 'winetricks -q d3dx9 && wineserver --wait' && 	su -p -l wine -c 'winetricks -q directplay && wineserver --wait' && 	apt-get autoremove -y --purge software-properties-common && 	apt-get autoremove -y --purge && 	apt-get clean -y && 	rm -rf /home/wine/.cache && 	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 2

**Comment by webanck** [comment]
Should be fixed now.
