### ISSUE TITLE
Build.sh stops because UID is readonly variable

### ISSUE THREAD

**Issue by tomoki** [webanck/docker-wine-steam#4]
Hi. Thank you for great tools.

When I run `build.sh`, I got following error.
```
./builder.sh: line 4: UID: readonly variable
```
I found that `$UID` is already assigned to `1000`, and I can remove line 4.

So, we should check whether `$UID` is empty or not like following:
```{.sh}
if [ -z "$UID" ]; then
    UID=`id -u`
fi
```
I confirm it works in my system, but not other systems (i.e Ubuntu or ...)

My system is
- Arch linux 64bit
- Shell is `zsh`

**Comment by webanck** [comment]
Well, I didn't know read only variables existed in shell ^^.
I changed the name of the variable to MYUID.
Can you confirm it does the job? I don't have any Arch at hand.

**Comment by tomoki** [comment]
I confirmed that it works as we expected.
Thanks for fix!
