### ISSUE TITLE
INFO[0000] [8] System error: exec format error  

### ISSUE THREAD

**Issue by Peterede** [webanck/docker-wine-steam#8]
When running on Dell laptop running Ubuntu 15.04 32-bit:

Sending build context to Docker daemon 16.38 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu
 ---> 08881219da4a
Step 1 : MAINTAINER Antoine Webanck <antoine.webanck@gmail.com>
 ---> Using cache
 ---> a69268f7c24c
Step 2 : RUN useradd -u 1000 -d /home/wine -m -s /bin/bash wine
 ---> Running in 95caf7824fd2
INFO[0000] [8] System error: exec format error

**Comment by webanck** [comment]
Hello, can you please try to replace the line ```#!/bin/bash``` by ```#!/bin/sh``` in the file [finalize_installation.sh](./finalize_installation.sh) and try again?
Also, what is your version of Docker?

**Comment by bugchecker** [comment]
You should use 32-bit containers, for example:
```
FROM 32bit/ubuntu
```
```
FROM ioft/i386-ubuntu
```
```
FROM prateekgogia/ubuntu32
```
32-bit doesn't have official support from Docker Inc.

**Comment by parikshit10** [comment]
#!/bin/sh

# Using official python runtime base image

FROM python:3

# Set the application directory
WORKDIR /app

# Install our requirements.txt

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy our code from the current folder to /app inside the container
COPY . /app

# Define our command to be run when launching the container

CMD ["sh", "./runningSript.sh"]

Hi, this is my docker file but when I am building the docker file using docker build. I am getting 
[8] System error: exec format error at step number 3 that is the installation of the requirement. Kindly help?
